### ISSUE TITLE
Is the Demo from the Pangeo Weekly meeting available/runnable? 

### ISSUE THREAD

**Issue by rsignell** [keewis/stac-insitu#1]
@keewis , I wonder if the nice little demo of stac-insitu you showed last week at the Pangeo Community Meeting is available?  I'd love to show it to the [NATO CMRE](https://www.cmre.nato.int) folks I meet with each Wednesday.  :)

**Comment by keewis** [comment]
not yet, no. The data itself is (effectively) public so it should be possible to publish, but I'll need to figure out how to host a STAC API endpoint (or write setup instructions so you can build your own STAC catalog). I've been away this week (hence why I missed the meeting on Wednesday), so I'll try to figure that out once I'm back at work next week.

**Comment by rsignell** [comment]
@keewis , okay great!   Enjoy your time away!

**Comment by keewis** [comment]
so... in theory you could use the [recipe](https://github.com/keewis/stac-insitu/blob/fddadec0024a6fc9fae78e1bc4e8d23b0dc29673/recipes/by_category.py) to create your own catalog, ingest it into the database of a STAC API endpoint, and then point the [demo](https://github.com/keewis/stac-insitu/blob/6facb7da54c074dd37447d9cf5d66e061317c885/search-catalog.ipynb) at that API.

However, there's a lot of files on the server, so with the somewhat slow HTTP server creating the catalog takes a fair amount of time. (I'm also not an expert on running `beam` pipelines so there might be some potential for optimization there).

I'm currently somewhat undecided on whether it is a better idea to publicly expose a STAC API endpoint somewhere (so the demo can make use of a larger dataset), or to add a separate recipe that selects just 2-3 months of data. The latter is significantly less effort for me, but in addition to running the recipe you'd also have to set up a STAC API endpoint – which is not that easy.

**Comment by rsignell** [comment]
@keewis, easier for you sounds good to me!   😸 
Also I've been looking for an excuse to set up a STAC API endpoint!  🤓 
We could set one up pointing at data on our open storage network pod so there would be no egress fees for data access...

**Comment by keewis** [comment]
if you have time-varying data (that forms trajectories) somewhere, sure.

Otherwise the server I'm currently using is a public HTTP server. Definitely not the fastest option, but it should allow you to avoid those fees (if I understand correctly, cloud computing is still somewhat new to me).

**Comment by rsignell** [comment]
I've done a lot of work with the US-IOOS community, and they have a lot of glider data that would be fun to try with!

**Comment by keewis** [comment]
I only looked at the [copernicus marine in-situ TAC](https://www.marineinsitu.eu/dashboard/) ([data server](https://data-marineinsitu.ifremer.fr/)). That does have gliders, as well, so not sure if that's the same data.

**Comment by rsignell** [comment]
@keewis , has the server moved again?

https://gfts-stac.duckdns.org/stac-sst-insitu/api/v1/   is returning 502

**Comment by keewis** [comment]
not that I know of. Let me check the server logs.

**Comment by keewis** [comment]
works again for me

**Comment by rsignell** [comment]
Yes, *now* it's working.  You didn't restart it or something?

**Comment by keewis** [comment]
yes, I did. There were some problems with one of the internal services that didn't start properly
